# Created by Jekyll Writer
title: Shian's Blog
author: Shian Liao
description: >
  This theme is disigned based on Mailbox Blog, and licensed under MIT. This
  theme is also default theme for new site created by Jekyll Writer.
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: jekyllwriter
github_username: liaoshian
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: /blog
